"""Russian word of the day — generated by Claude Haiku, rotating through beginner categories."""

import json
import os
from datetime import datetime

import anthropic

CATEGORIES = [
    "greetings (Привет, Здравствуйте, Доброе утро, До свидания, Пока, Спокойной ночи)",
    "politeness words (Спасибо, Пожалуйста, Извините, Не за что, Ладно)",
    "basic pronouns (Я, Ты, Он, Она, Мы, Вы, Они)",
    "introductions and names (Меня зовут, Я из, Как вас зовут?)",
    "question words (Что, Кто, Где, Когда, Почему, Как, Сколько)",
    "yes/no and simple responses (Да, Нет, Конечно, Может быть, Не знаю)",
    "numbers 1-5 (один, два, три, четыре, пять)",
    "numbers 6-10 (шесть, семь, восемь, девять, десять)",
    "days of the week (понедельник, вторник, среда, четверг, пятница, суббота, воскресенье)",
    "time words (Сегодня, Завтра, Вчера, Сейчас, Потом)",
    "essential verbs: being and having (быть, иметь, знать, понимать)",
    "essential verbs: actions (говорить, делать, идти, работать, жить)",
    "essential verbs: wants and feelings (хотеть, любить, видеть, думать)",
    "common nouns: people (человек, друг, семья, мать, отец)",
    "common nouns: places (дом, город, улица, магазин, ресторан)",
    "common nouns: food and drink (вода, хлеб, кофе, чай, еда)",
    "common nouns: everyday objects (деньги, время, телефон, книга, машина)",
    "adjectives: size and age (большой, маленький, новый, старый)",
    "adjectives: quality (хороший, плохой, красивый, интересный)",
    "adjectives: temperature and feel (горячий, холодный, быстрый, медленный)",
    "practical phrases: getting around (Где туалет?, Где метро?, Как пройти?)",
    "practical phrases: shopping (Сколько это стоит?, Счёт пожалуйста, Дорого, Дёшево)",
    "practical phrases: understanding (Я не понимаю, Повторите пожалуйста, Говорите медленнее)",
    "practical phrases: daily life (Как дела?, Всё хорошо, Что это?, Помогите пожалуйста)",
]

PROMPT = """\
You are a Russian language tutor helping an English-speaking beginner who is learning Russian from his Russian-speaking girlfriend.

Today's category to focus on: {category}

Generate ONE word or short phrase from this category that is genuinely useful for a beginner.
Pick something specific and practical — not too abstract.

Today's date: {date} (use this to avoid repeating recent words — vary your pick day to day).

Return ONLY valid JSON, no markdown, no explanation:
{{
  "russian": "the word or phrase in Cyrillic script",
  "transliteration": "phonetic English pronunciation guide (e.g. 'zdra-STVUY-tye')",
  "english": "English translation",
  "explanation": "2-3 sentences explaining the word, when to use it, any important notes about pronunciation or grammar, and one simple example sentence in Russian followed by its English translation in parentheses"
}}"""


def get_russian_word():
    try:
        today = datetime.now()
        day_of_year = today.timetuple().tm_yday
        category = CATEGORIES[day_of_year % len(CATEGORIES)]

        client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=400,
            messages=[{"role": "user", "content": PROMPT.format(
                category=category,
                date=today.strftime("%B %d, %Y"),
            )}],
        )
        raw = msg.content[0].text.strip()
        if raw.startswith("```"):
            raw = "\n".join(raw.split("\n")[1:])
            if raw.endswith("```"):
                raw = raw[:-3]
        data = json.loads(raw)
        print(f"Russian: {data.get('russian')} — {data.get('english')}")
        return data
    except Exception as e:
        print(f"Russian word error: {e}")
        return None
